apiVersion: v1
kind: ConfigMap
metadata:
  name: eventfund-backend-config
data:
  NODE_ENV: "${NODE_ENV}"
  PORT: "${BACKEND_PORT}"
  LOG_LEVEL: "${LOG_LEVEL}"
  RATE_LIMIT_WINDOW_MS: "${RATE_LIMIT_WINDOW_MS}"
  RATE_LIMIT_MAX_REQUESTS: "${RATE_LIMIT_MAX_REQUESTS}"
  AUTH_RATE_LIMIT_MAX: "${AUTH_RATE_LIMIT_MAX}"
  MIN_DEPOSIT_VND: "${MIN_DEPOSIT_VND}"
  MAX_DEPOSIT_VND: "${MAX_DEPOSIT_VND}"
  DEPOSIT_ORDER_EXPIRY_MINUTES: "${DEPOSIT_ORDER_EXPIRY_MINUTES}"
  AUTO_EVENT_LIFECYCLE_ENABLED: "${AUTO_EVENT_LIFECYCLE_ENABLED}"
  AUTO_EVENT_LIFECYCLE_INTERVAL_MS: "${AUTO_EVENT_LIFECYCLE_INTERVAL_MS}"
  AUTO_EVENT_LIFECYCLE_SCAN_LIMIT: "${AUTO_EVENT_LIFECYCLE_SCAN_LIMIT}"
  AUTO_TICKETING_DEFAULT_TYPE: "${AUTO_TICKETING_DEFAULT_TYPE}"
  CHAIN_LOG_CHUNK_SIZE: "${CHAIN_LOG_CHUNK_SIZE}"
  JWT_EXPIRES_IN: "${JWT_EXPIRES_IN}"
  SIWE_CHAIN_ID: "${SIWE_CHAIN_ID}"
  DELEGATED_SIG_CHAIN_ID: "${DELEGATED_SIG_CHAIN_ID}"
  DELEGATED_SIG_DOMAIN_NAME: "${DELEGATED_SIG_DOMAIN_NAME}"
  DELEGATED_SIG_DOMAIN_VERSION: "${DELEGATED_SIG_DOMAIN_VERSION}"
  RELAYER_REQUIRE_CREATE_EVENT_SIGNATURE: "${RELAYER_REQUIRE_CREATE_EVENT_SIGNATURE}"
  RELAYER_REQUIRE_ADMIN_STATUS_SIGNATURE: "${RELAYER_REQUIRE_ADMIN_STATUS_SIGNATURE}"
  CONTRACTS_ARTIFACTS_DIR: "${CONTRACTS_ARTIFACTS_DIR}"
  WEB3AUTH_NETWORK: "${WEB3AUTH_NETWORK}"
