apiVersion: v1
kind: ConfigMap
metadata:
  name: eventfund-backend-config
data:
  NODE_ENV: "${NODE_ENV}"
  PORT: "${BACKEND_PORT}"
  LOG_LEVEL: "${LOG_LEVEL}"
  AUTO_EVENT_LIFECYCLE_ENABLED: "${AUTO_EVENT_LIFECYCLE_ENABLED}"
  AUTO_EVENT_LIFECYCLE_INTERVAL_MS: "${AUTO_EVENT_LIFECYCLE_INTERVAL_MS}"
  AUTO_EVENT_LIFECYCLE_SCAN_LIMIT: "${AUTO_EVENT_LIFECYCLE_SCAN_LIMIT}"
  AUTO_TICKETING_DEFAULT_TYPE: "${AUTO_TICKETING_DEFAULT_TYPE}"
  CHAIN_LOG_CHUNK_SIZE: "${CHAIN_LOG_CHUNK_SIZE}"
  CONTRACTS_ARTIFACTS_DIR: "${CONTRACTS_ARTIFACTS_DIR}"
