

project:
  name: eventfund
  environment: dev

environments:
  dev:
    branch: dev
  prod:
    branch: master

terraform:
  eks_version: "1.33"
  node_instance_type: m7i-flex.large
  node_desired_capacity: 2
  node_min_capacity: 1
  node_max_capacity: 4
  terraform_version: "1.7.0"
  security_reports_retention_days: 15

k8s:
  backend_port: "4000"
  log_level: info
  auto_event_lifecycle_enabled: "true"
  auto_event_lifecycle_interval_ms: "60000"
  auto_event_lifecycle_scan_limit: "50"
  auto_ticketing_default_type: standard
  chain_log_chunk_size: "500"
  contracts_artifacts_dir: ./artifacts

argocd:
  repo_url: https://github.com/truongtrongdat94/Eventfund-platform.git
  target_revision: dev

sonarcloud:
  project_key: truongtrongdat94_eventfund-platform
  organization: truongtrongdat94
  base_url: https://sonarcloud.io

node:
  version: "20.19.0"

docker:
  buildx_version: v0.12.0

timeouts:
  health_check_seconds: 180
  health_check_retries: 60
  deploy_wait_seconds: 300
  deploy_wait_retries: 30

security_scans:
  trivy:
    severity: "CRITICAL,HIGH"
    format: "sarif"
  owasp:
    format: "HTML,JSON,XML"
    retention_days: 30
  sonarqube:
    retention_days: 30
