name: Manual – SonarQube Scan

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sonarqube-scan:
    uses: ./.github/workflows/reusable-scan-sonarqube.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
